name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - run: ./text-match.js solar-system.txt "largest planet" | tee output.txt | grep -i "Jupiter"

    - run: cat output.txt
      if: always()
